// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgmvWzBTNdDFlld7OsEKs4U9DP4u8vy9g',
    appId: '1:1059253142118:web:59dbf184a6aa1b9b9ae3a7',
    messagingSenderId: '1059253142118',
    projectId: 'mhis-employee',
    authDomain: 'mhis-employee.firebaseapp.com',
    storageBucket: 'mhis-employee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC0G0-iYZiJOLIsnbFzYNrcM93XQSSR80',
    appId: '1:1059253142118:android:616957cc1efff76b9ae3a7',
    messagingSenderId: '1059253142118',
    projectId: 'mhis-employee',
    storageBucket: 'mhis-employee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB845oghvP8Z9Okjefpjj7w8YtjQe0x_hw',
    appId: '1:1059253142118:ios:e0813a24c04272519ae3a7',
    messagingSenderId: '1059253142118',
    projectId: 'mhis-employee',
    storageBucket: 'mhis-employee.appspot.com',
    iosBundleId: 'com.example.flMhisHr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB845oghvP8Z9Okjefpjj7w8YtjQe0x_hw',
    appId: '1:1059253142118:ios:e0813a24c04272519ae3a7',
    messagingSenderId: '1059253142118',
    projectId: 'mhis-employee',
    storageBucket: 'mhis-employee.appspot.com',
    iosBundleId: 'com.example.flMhisHr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgmvWzBTNdDFlld7OsEKs4U9DP4u8vy9g',
    appId: '1:1059253142118:web:05c2e22a2c5560959ae3a7',
    messagingSenderId: '1059253142118',
    projectId: 'mhis-employee',
    authDomain: 'mhis-employee.firebaseapp.com',
    storageBucket: 'mhis-employee.appspot.com',
  );
}
