// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeE_zt-z_xAKg9STjjhdNln_pazVyRXR8',
    appId: '1:570915657063:web:fa1f190a3432ba7d304bc2',
    messagingSenderId: '570915657063',
    projectId: 'mhportalemployee',
    authDomain: 'mhportalemployee.firebaseapp.com',
    storageBucket: 'mhportalemployee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhiCUp8K_37LOVSKwAwfWH7m5px0npTj4',
    appId: '1:570915657063:android:b86d1ac7a5d8f33d304bc2',
    messagingSenderId: '570915657063',
    projectId: 'mhportalemployee',
    storageBucket: 'mhportalemployee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYwmkX9I8g1koACZmzr-ZMXu8vQhq1Me8',
    appId: '1:570915657063:ios:d5541cd4c6d877c9304bc2',
    messagingSenderId: '570915657063',
    projectId: 'mhportalemployee',
    storageBucket: 'mhportalemployee.appspot.com',
    iosBundleId: 'com.example.flMhisHr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYwmkX9I8g1koACZmzr-ZMXu8vQhq1Me8',
    appId: '1:570915657063:ios:d5541cd4c6d877c9304bc2',
    messagingSenderId: '570915657063',
    projectId: 'mhportalemployee',
    storageBucket: 'mhportalemployee.appspot.com',
    iosBundleId: 'com.example.flMhisHr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeE_zt-z_xAKg9STjjhdNln_pazVyRXR8',
    appId: '1:570915657063:web:3b555845a965b840304bc2',
    messagingSenderId: '570915657063',
    projectId: 'mhportalemployee',
    authDomain: 'mhportalemployee.firebaseapp.com',
    storageBucket: 'mhportalemployee.appspot.com',
  );

}