// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ7kMinTZzo-c_VHa3Uh38OwlEDhhugWA',
    appId: '1:592617177680:web:97aa15a67c3a18bbc74755',
    messagingSenderId: '592617177680',
    projectId: 'mhis-hub',
    authDomain: 'mhis-hub.firebaseapp.com',
    storageBucket: 'mhis-hub.appspot.com',
    measurementId: 'G-NQZNBXV7Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp8sQ47a2rM0IsWkjxSscDfHOiZ9Qs6io',
    appId: '1:592617177680:android:7531ee003c0181c0c74755',
    messagingSenderId: '592617177680',
    projectId: 'mhis-hub',
    storageBucket: 'mhis-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfGEetLgIRpQ6gsm2smoOtFQEjEqfZDt4',
    appId: '1:592617177680:ios:8bf1acab94d8c239c74755',
    messagingSenderId: '592617177680',
    projectId: 'mhis-hub',
    storageBucket: 'mhis-hub.appspot.com',
    iosBundleId: 'com.mhis.hris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfGEetLgIRpQ6gsm2smoOtFQEjEqfZDt4',
    appId: '1:592617177680:ios:8bf1acab94d8c239c74755',
    messagingSenderId: '592617177680',
    projectId: 'mhis-hub',
    storageBucket: 'mhis-hub.appspot.com',
    iosBundleId: 'com.mhis.hris',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ7kMinTZzo-c_VHa3Uh38OwlEDhhugWA',
    appId: '1:592617177680:web:56e85b3184cc4f19c74755',
    messagingSenderId: '592617177680',
    projectId: 'mhis-hub',
    authDomain: 'mhis-hub.firebaseapp.com',
    storageBucket: 'mhis-hub.appspot.com',
    measurementId: 'G-QV54KPC0JB',
  );
}
